### ISSUE TITLE
Guides: incorrect display of the JMP Terezín collection

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#553]
Please see for instance:

http://portal.aehri.dans.knaw.nl/guides/terezin/browse?q=&kw=&kw=&kw=terezin-victims-person-iti-1296855&kw=

The breadcrumb for the JMP Terezín/Theresienstadt collection is displayed incorrectly, it seems to me that one level is left out, for instance here:

    Židovské muzeum v Praze
    cz-002279-collection-jmp-shoah-t-collection-jmp-shoah-t-2-collection-jmp-shoah-t-2-a
    Terezín ghetto – Leadership of the Jewish self-government (Leitung – L)
    Official records – (Aktenvermerke)
    Official minutes of meetings held by the Jewish Council of Eldersat the camp commander’s office and records of mail handed over– Economic Department
    1) W: No. W 720 – 927

It seems that "cz-002279-collection-jmp-shoah-t-collection-jmp-shoah-t-2-collection-jmp-shoah-t-2-a" mixes up more levels (Terezín/Theresienstadt / Documents / Documents from the period of occupation). Might this problem (which I have already reported a couple of times) be related to the slash in the collection name?

**Comment by mikesname** [comment]
Fixed by increasing serialization depth on the backend.

**Comment by mikesname** [comment]
@michalfrankl at least I think this is fixed. Don't quite understand what you mean by "mixes up more levels"? Please check.

**Comment by michalfrankl** [comment]
It seems I can't check it on staging now, as the JMP Terezín data isn't there. The problem still persists on production. Is there any risk in pushing your fix to production now? I'll make sure to check it looks ok.

**Comment by mikesname** [comment]
@michalfrankl  Sorry I had to revert this due to unexpected problems. It's a small fix that will go out soon with some other updates.

**Comment by michalfrankl** [comment]
OK, thanks, please just make sure it's out for Berlin.

**Comment by mikesname** [comment]
Now on production and staging.

**Comment by michalfrankl** [comment]
Thanks, looks good to me.
